- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

    - name: remap CapsLock to Super
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:super']"
        state: present

  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/containers.yml

