- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=no
      changed_when: False

  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/containers.yml

