- hosts: localhost
  become: true
  pre_tasks:
    - name: add Tailscale GPG key
      apt_key:
        url: https://pkgs.tailscale.com/stable/ubuntu/focal.noarmor.gpg
        state: present
    - name: add Tailscale repository
      apt_repository:
        repo: https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscae-keyring.list
        filename: tailscale
        state: present
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

    - name: remap CapsLock to Super
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:super']"
        state: present

  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/users.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/containers.yml

