- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=no
      changed_when: False

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml

