  - name: Containers - Jellyfin
    docker_container:
      image: lscr.io/linuxserver/jellyfin:latest
      name: jellyfin
      state: started
      env:
        PUID: "1000"
        PGID: "1000"
        TZ: "America/New_York"
      volumes:
        - /home/chris/jellyfin/config:/config
        - /mnt/fusion/Movies:/data/movies
        - /mnt/fusion/TV Shows:/data/tvshows
        - /mnt/fusion/Music:/data/music
      ports:
        - "8096:8096"
        - "8920:8920"
        - "7359:7359"
        - "1900:1900"
      restart_policy: unless-stopped

  - name: Containers - MariaDB (for Nextcloud)
    docker_container:
      image: lscr.io/linuxserver/mariadb:latest
      name: mariadb
      state: started
      env:
        PUID: "1000"
        PGID: "1000"
        TZ: "America/New_York"
        MYSQL_ROOT_PASSWORD: mariadbpassword #change this to vault at some point
        MYSQL_DATABASE: nextcloud-db
        MYSQL_USER: nextcloud
        MYSQL_PASSWORD: nextclouddbpassword #change this to vault at some point
      volumes:
        - /home/chris/mariadb/config:/config
      ports:
        - 3306:3306
      restart_policy: unless-stopped

  - name: Containers - Nextcloud
    docker_container:
      image: lscr.io/linuxserver/nextcloud:latest
      name: nextcloud
      state: started
      env:
        PUID: "1000"
        PGID: "1000"
        TZ: "America/New_York"
      volumes:
        - /home/chris/nextcloud/config:/config
        - /mnt/fusion/nextcloud:/data
      ports:
        - 443:443
      restart_policy: unless-stopped

#      - name: Containers - Tandoor
#        docker_container:
#          image:
#          name:
#          state:
#          env:
#          volumes:
#          ports:
#          restart_policy: unless-stopped