
- name: Packages - VirtualBox
  apt:  
    name: virtualbox-qt
    state: latest

- name: Packages - GUI apps
  apt:
    name: [
     'gparted',
     'inkscape',
     'solaar',
     'audacity',
     'gimp',
     'conky',
    ]
    state: latest

- name: Packages - CLI apps
  apt:
    name: [
     'byobu',
     'cmus',
     'iotop',
     'mmv',
     'mpv',
     'ncdu',
     'htop',
     'tmux',
    ]
    state: latest

- name: Packages - Filesystems & backups
  apt:
    name: [
     'mergerfs',
     'restic',
    ]
    state: latest
