
- name: Packages - VirtualBox
  apt:  
    name: virtualbox-qt
    state: latest

- name: Packages - GUI apps
  apt:
    name: [
     'gparted',
     'inkscape',
     'solaar',
     'audacity',
     'gimp',
     'conky',
    ]
    state: latest

- name: Packages - CLI apps
  apt:
    name: [
     'byobu',
     'cmus',
     'iotop',
     'mmv',
     'mpv',
     'ncdu',
     'htop',
     'tmux',
    ]
    state: latest

- name: Packages - set up MergerFS
  apt:
    name: [
     'mergerfs',
    ]
    state: latest
  file:
    path: /mnt/
    state: directory
    mode: 0755
    with_items:
      - fusion
      - drive01


name: Packages - set up Restic
  apt:
    name: [
     'restic',
    ]
    state: latest