- name: Install apt packages
  apt:  
    name: [ 
    'htop',
    'tmux',
    'virtualbox-qt',
    'gimp',
    'gparted',
    'inkscape',
    'solaar',
    'audacity',
    'byobu',
    'cmus',
    'conky',
    'git',
    'gpg',
    'iotop',
    'mergerfs',
    'mmv',
    'mpv',
    'ncdu',
    'nemo',
    'openssh-server',
    'restic',
    'samba',
    'speedtest-cli',
    'steam-launcher',
    'tailscale',
    'testdisk',
    'todoist',
    'xbindkeys'
    ]
