- name: Install packages
   apt: name= {{item}}
   with_items:
    - htop
    - tmux
    - google-chrome-stable
    - virtualbox-qt
    - gimp
    - gparted
    - inkscape
    - solaar
    - authy
    - audacity
    - byobu
    - cmus
    - conky
    - docker-ce
    - git
    - filezilla
    - gpg
    - insync
    - iotop
    - jellyfin
    - mergerfs
    - mmv
    - mpv
    - ncdu
    - nemo
    - nomachine
    - openssh-server
    - restic
    - samba
    - speedtest-cli
    - steam-launcher
    - tailscale
    - testdisk
    - todoist
    - unison
    - wireguard
    - xbindkeys
